new Vue({
    el:'#app',
    data(){
        return{
            list:[
                {
                    tit:'分类1',
                    con:'撒打算打算1'
                },
                {
                    tit:'分类2',
                    con:'撒打算打算2'
                },
                {
                    tit:'分类3',
                    con:'撒打算打算3'
                },
                {
                    tit:'分类4',
                    con:'撒打算打算4'
                },
                {
                    tit:'分类5',
                    con:'撒打算打算5'
                },
            ],
            // tab切换的下标
            tabIndex:0,
        }
    }
})